version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin #sim, coloque uma senha forte
      MYSQL_DATABASE: database_products
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin #sim, coloque uma senha forte
    networks:
      - my_network

  scrapingpython:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
