version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin #sim, coloque uma senha forte

  scrapingpython:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
