version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: database_products
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  scrapingpython:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

