version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "localhost:27017"
    restart: always

  scrapingpython:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
