version: '3'
services:
  my_service:
    build: .
    volumes:
      - ./urls.txt:/app/urls.txt
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
